version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://db:27017/digitaldisplay
      - PORT=3001
      - ENVIRON=DEV
      - SESSION_SECRET=your_session_secret
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:

